### ISSUE TITLE
Deployment framework

### ISSUE THREAD

**Issue by nicholasdille** [nicholasdille/k8s-templates#32]
Questions:
- [x] How to handle `kind`?
- [x] How to prepare cluster?
- [x] How to handle multiple configurations?

Implementation:
- Isolated directories calling each other to satisfy dependencies

Features:
- [x] `certificates` (standalone)
- [x] `dns` (standalone)
- [x] `ingress` (standalone)
- [x] `ingress/https`
- [x] `ingress/dns` (enabled by cluster feature `dns`)
- [x] `ingress/certificate` (enabled by cluster feature `certificates`)
- [x] `ingress/monitoring` (enabled by cluster feature `monitoring`)
- [x] `monitoring`
- [x] `monitoring/ingress` (enabled by cluster feature `ingress`)
- [x] `monitoring/ui` (only possible with cluster feature `ingress/http`)
- [x] `auth` (only possible with cluster features `ingress/https`)

Tasks:
- [ ] Test
- [x] ~Separate templating and deployment~ (now #43)
- [x] ~Integrate into build system~ (now #44)
- [x] ~Integrate into automated tests~ (now #24)
